// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: typeof import('./src/baseComponents/svgIcon/SvgIcon.vue')['default']
    Three: typeof import('./src/baseComponents/three/Three.vue')['default']
    WeSwitch: typeof import('./src/baseComponents/weSwitch/WeSwitch.vue')['default']
  }
}

export {}
