// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/baseComponents/parallaxDepthCard/Card.vue')['default']
    Footer: typeof import('./src/baseComponents/footer/Footer.vue')['default']
    ParallaxDepthCard: typeof import('./src/baseComponents/parallaxDepthCard/ParallaxDepthCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/baseComponents/searchBar/SearchBar.vue')['default']
    SvgIcon: typeof import('./src/baseComponents/svgIcon/SvgIcon.vue')['default']
    Three: typeof import('./src/baseComponents/three/Three.vue')['default']
    WeSwitch: typeof import('./src/baseComponents/weSwitch/WeSwitch.vue')['default']
  }
}

export {}
